### ISSUE TITLE
Ident authentication fails when I connect to Postgres as a different user

### ISSUE THREAD

**Issue by 5x3** [openstreetmap/openstreetmap-website#2045]
Debian 9.5 (last upgraded and dist-upgraded) fresh install
following official steps here https://github.com/openstreetmap/openstreetmap-website/blob/master/INSTALL.md

```
root@debian:~/openstreetmap-website# sudo -u postgres -i
postgres@debian:~$ createuser -s openstreetmap
exit;

```

```
root@debian:~/openstreetmap-website# head config/database.yml 
# Using a recent release (9.1 or higher) of PostgreSQL (http://postgresql.org/) is recommended.
# See https://github.com/openstreetmap/openstreetmap-website/blob/master/INSTALL.md#database-setup for detailed setup instructions.
#
development:
  adapter: postgresql
  database: openstreetmap
  username: openstreetmap
  #password: openstreetmap
#  host: localhost
  encoding: utf8
root@debian:~/openstreetmap-website# 
```

```
root@debian:~/openstreetmap-website# bundle exec rake db:create 
pngcrush worker: `pngcrush` not found; please provide proper binary or disable this worker (--no-pngcrush argument or `:pngcrush => false` through options)
advpng worker: `advpng` not found; please provide proper binary or disable this worker (--no-advpng argument or `:advpng => false` through options)
optipng worker: `optipng` not found; please provide proper binary or disable this worker (--no-optipng argument or `:optipng => false` through options)
pngquant worker: `pngquant` not found; please provide proper binary or disable this worker (--no-pngquant argument or `:pngquant => false` through options)
jhead worker: `jhead` not found, `jpegtran` not found; please provide proper binary or disable this worker (--no-jhead argument or `:jhead => false` through options)
jpegoptim worker: `jpegoptim` not found; please provide proper binary or disable this worker (--no-jpegoptim argument or `:jpegoptim => false` through options)
jpegtran worker: `jpegtran` not found; please provide proper binary or disable this worker (--no-jpegtran argument or `:jpegtran => false` through options)
gifsicle worker: `gifsicle` not found; please provide proper binary or disable this worker (--no-gifsicle argument or `:gifsicle => false` through options)
svgo worker: `svgo` not found; please provide proper binary or disable this worker (--no-svgo argument or `:svgo => false` through options)
FATAL:  Peer authentication failed for user "openstreetmap"
Couldn't create database for {"adapter"=>"postgresql", "database"=>"openstreetmap", "username"=>"openstreetmap", "encoding"=>"utf8"}
rake aborted!
PG::ConnectionBad: FATAL:  Peer authentication failed for user "openstreetmap"
/var/lib/gems/2.3.0/gems/pg-0.21.0/lib/pg.rb:56:in `initialize'
/var/lib/gems/2.3.0/gems/pg-0.21.0/lib/pg.rb:56:in `new'
/var/lib/gems/2.3.0/gems/pg-0.21.0/lib/pg.rb:56:in `connect'
/var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:684:in `connect'
/var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:215:in `initialize'
/var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:40:in `new'
/var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:40:in `postgresql_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:809:in `new_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `checkout_new_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:832:in `try_to_checkout_new_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:793:in `acquire_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:521:in `checkout'
/var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:380:in `connection'
/var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:1008:in `retrieve_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_handling.rb:90:in `connection'
/var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection'
/var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
/var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:119:in `create'
/var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:139:in `block in create_current'
/var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:316:in `block in each_current_configuration'
/var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:313:in `each'
/var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:313:in `each_current_configuration'
/var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:138:in `create_current'
/var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/railties/databases.rake:29:in `block (2 levels) in <main>'
/var/lib/gems/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:create
(See full trace by running task with --trace)
root@debian:~/openstreetmap-website# 

```

what else should be done to successfully execute  "bundle exec rake db:create" ?

**Comment by 5x3** [comment]
thanks. working.
I found that accessing main page takes too long sometimes, but sometimes its OK
why this can be?

bob@debian:~$ time curl -v 127.0.0.1:3000
..
real	0m4.516s
user	0m0.004s
sys	0m0.000s

real	0m0.547s
user	0m0.004s
sys	0m0.008s
worker@debian:~$ time curl -v 127.0.0.1:3000

**Comment by gravitystorm** [comment]
Great to hear that it's now working. 

For debugging the slow load times, I would have a look at the development log (in the `log` directory) and see if you can see any causes. There are also some things (like first page load) that run more slowly in the development environment than in production, so it's worth being aware of that too.

**Comment by tomhughes** [comment]
If you're using the basic rails server then it can be quite slow because it's single threaded I think so it can only process one request at a time, plus in development mode each resource is fetched separately so it can be quite slow especially at first until all the various CSS and javascript resources have been cached.

**Comment by 5x3** [comment]
RAILS_ENV=production bundle exec rails server
starts OK but
when I invoke
curl -v http://127.0.0.1:3000


```
bob@openstreetmap:~/openstreetmap-website# cat log/production.log 
I, [2018-11-06T09:32:11.893531 #1990]  INFO -- :   Message: getpresets
W, [2018-11-06T09:32:12.077609 #1990]  WARN -- : Creating scope :open. Overwriting existing method Issue.open.
I, [2018-11-06T09:32:15.847575 #1990]  INFO -- : [67625fa4-dce7-4afb-8cce-3e00f40cf072] Started GET "/" for 127.0.0.1 at 2018-11-06 09:32:15 -0500
I, [2018-11-06T09:32:15.900328 #1990]  INFO -- : [67625fa4-dce7-4afb-8cce-3e00f40cf072] Processing by SiteController#index as */*
I, [2018-11-06T09:32:17.022691 #1990]  INFO -- : [67625fa4-dce7-4afb-8cce-3e00f40cf072]   Rendering site/index.html.erb within layouts/map
I, [2018-11-06T09:32:17.023587 #1990]  INFO -- : [67625fa4-dce7-4afb-8cce-3e00f40cf072]   Rendered site/index.html.erb within layouts/map (0.7ms)
I, [2018-11-06T09:32:17.028594 #1990]  INFO -- : [67625fa4-dce7-4afb-8cce-3e00f40cf072] Completed 500 Internal Server Error in 1128ms
F, [2018-11-06T09:32:17.029322 #1990] FATAL -- : [67625fa4-dce7-4afb-8cce-3e00f40cf072]   
F, [2018-11-06T09:32:17.029357 #1990] FATAL -- : [67625fa4-dce7-4afb-8cce-3e00f40cf072] ActionView::Template::Error (The asset "index.js" is not present in the asset pipeline.):
F, [2018-11-06T09:32:17.029485 #1990] FATAL -- : [67625fa4-dce7-4afb-8cce-3e00f40cf072]     1: <% content_for :head do %>
[67625fa4-dce7-4afb-8cce-3e00f40cf072]     2:   <%= javascript_include_tag "index" %>
[67625fa4-dce7-4afb-8cce-3e00f40cf072]     3: <% end %>
[67625fa4-dce7-4afb-8cce-3e00f40cf072]     4: 
[67625fa4-dce7-4afb-8cce-3e00f40cf072]     5: <% content_for(:body_class) { "map-layout" } %>
F, [2018-11-06T09:32:17.029516 #1990] FATAL -- : [67625fa4-dce7-4afb-8cce-3e00f40cf072]   
F, [2018-11-06T09:32:17.029537 #1990] FATAL -- : [67625fa4-dce7-4afb-8cce-3e00f40cf072] app/views/layouts/map.html.erb:2:in `block in _app_views_layouts_map_html_erb___2600159433901687752_47157810216420'
[67625fa4-dce7-4afb-8cce-3e00f40cf072] app/views/layouts/map.html.erb:1:in `_app_views_layouts_map_html_erb___2600159433901687752_47157810216420'
[67625fa4-dce7-4afb-8cce-3e00f40cf072] config/initializers/cors.rb:9:in `call'
[67625fa4-dce7-4afb-8cce-3e00f40cf072] config/initializers/compressed_requests.rb:27:in `call'
I, [2018-11-06T09:32:17.030269 #1990]  INFO -- : [67625fa4-dce7-4afb-8cce-3e00f40cf072] Processing by ErrorsController#internal_server_error as */*
I, [2018-11-06T09:32:17.034552 #1990]  INFO -- : [67625fa4-dce7-4afb-8cce-3e00f40cf072]   Rendering errors/internal_server_error.html.erb within layouts/error
I, [2018-11-06T09:32:17.034871 #1990]  INFO -- : [67625fa4-dce7-4afb-8cce-3e00f40cf072]   Rendered errors/internal_server_error.html.erb within layouts/error (0.2ms)
I, [2018-11-06T09:32:17.038324 #1990]  INFO -- : [67625fa4-dce7-4afb-8cce-3e00f40cf072] Completed 500 Internal Server Error in 8ms
bob@openstreetmap:~/openstreetmap-website# 

```

**Comment by gravitystorm** [comment]
@5x3 You'll need to precompile the assets for use in production.

In general, we provide support for setting up development environments to get you to the point where you can start hacking on the code and submitting patches. We don't have enough volunteers to provide support beyond this stage though!
