### ISSUE TITLE
Error during failsafe response: Missing template errors/not_found, application/not_found with {:locale=>[:en], :formats=>[:css], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jsonify, :coffee]}.

### ISSUE THREAD

**Issue by RanQiwu** [openstreetmap/openstreetmap-website#2092]
Dockerfile:

```
FROM phusion/passenger-ruby24

WORKDIR /home
RUN git clone --depth=1 https://github.com/openstreetmap/openstreetmap-website.git\
&& cd openstreetmap-website\
&& echo "gem 'tzinfo-data'" >> Gemfile\
&& bundle install\
&& cp config/example.application.yml config/application.yml\
&& cp config/example.database.yml config/database.yml\
&& bundle exec rake i18n:js:export\
&& bundle exec rake assets:precompile\
&& apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /home/openstreetmap-website
CMD RAILS_ENV=production bundle exec rails server
```

The following error occurred while running the container and request http://ip:3000:
```
=> Booting Puma
=> Rails 5.2.2 application starting in production
Puma starting in single mode...
* Version 3.12.0 (ruby 2.4.5-p335), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: production
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
Error during failsafe response: Missing template errors/not_found, application/not_found with {:locale=>[:en], :formats=>[:css], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jsonify, :coffee]}. Searched in:
  * "/home/openstreetmap-website/app/views"

  /usr/local/rvm/gems/ruby-2.4.5/gems/actionview-5.2.2/lib/action_view/path_set.rb:48:in `find'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionview-5.2.2/lib/action_view/lookup_context.rb:116:in `find'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionview-5.2.2/lib/action_view/renderer/abstract_renderer.rb:20:in `find_template'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionview-5.2.2/lib/action_view/renderer/template_renderer.rb:40:in `determine_template'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionview-5.2.2/lib/action_view/renderer/template_renderer.rb:10:in `render'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionview-5.2.2/lib/action_view/renderer/renderer.rb:44:in `render_template'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionview-5.2.2/lib/action_view/renderer/renderer.rb:25:in `render'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionview-5.2.2/lib/action_view/rendering.rb:103:in `_render_template'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_controller/metal/streaming.rb:219:in `_render_template'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionview-5.2.2/lib/action_view/rendering.rb:84:in `render_to_body'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/abstract_controller/rendering.rb:25:in `render'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_controller/metal/rendering.rb:36:in `render'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
  /usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
  /usr/local/rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
  /usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/core_ext/benchmark.rb:14:in `ms'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_controller/metal/instrumentation.rb:46:in `block in render'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  /usr/local/rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/railties/controller_runtime.rb:36:in `cleanup_view_runtime'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_controller/metal/instrumentation.rb:45:in `render'
  /home/openstreetmap-website/app/controllers/errors_controller.rb:9:in `not_found'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/abstract_controller/base.rb:194:in `process_action'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
  /usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
  /usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:136:in `run_callbacks'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/abstract_controller/callbacks.rb:41:in `process_action'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_controller/metal/rescue.rb:22:in `process_action'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
  /usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/notifications.rb:168:in `block in instrument'
  /usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
  /usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/notifications.rb:168:in `instrument'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
  /usr/local/rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/abstract_controller/base.rb:134:in `process'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionview-5.2.2/lib/action_view/rendering.rb:32:in `process'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_controller/metal.rb:191:in `dispatch'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_controller/metal.rb:252:in `dispatch'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:34:in `serve'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_dispatch/journey/router.rb:52:in `block in serve'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_dispatch/journey/router.rb:35:in `each'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_dispatch/journey/router.rb:35:in `serve'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:840:in `call'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_dispatch/middleware/show_exceptions.rb:51:in `render_exception'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_dispatch/middleware/show_exceptions.rb:36:in `rescue in call'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  /usr/local/rvm/gems/ruby-2.4.5/gems/railties-5.2.2/lib/rails/rack/logger.rb:38:in `call_app'
  /usr/local/rvm/gems/ruby-2.4.5/gems/railties-5.2.2/lib/rails/rack/logger.rb:26:in `block in call'
  /usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/tagged_logging.rb:71:in `block in tagged'
  /usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/tagged_logging.rb:28:in `tagged'
  /usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/tagged_logging.rb:71:in `tagged'
  /usr/local/rvm/gems/ruby-2.4.5/gems/railties-5.2.2/lib/rails/rack/logger.rb:26:in `call'
  /usr/local/rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  /usr/local/rvm/gems/ruby-2.4.5/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'
```
How can I solve this problem?

**Comment by tomhughes** [comment]
No idea, but it works fine for me so it must be a problem with your environment.

That template should be present as `app/views/errors/not_found.html.erb` but it shouldn't be needed anyway if you are hitting a URL that exists.

It sounds like you have something very wrong.

Please note that the `Dockerfile` is pretty much unsupported as it not routinely used by any of the main developers and none of us knows anything much about docker.

**Comment by tomhughes** [comment]
Obvious issues are that it's unlikely that those two config files can be used without any editing, you don't seem to be doing anything to setup the database, and you're running in production which is probably stopping details of the real problem being reported - try running in development instead.

It's also often worth checking that `bundle exec rails console` works to get a console up before trying to run a web server and hit that.

**Comment by RanQiwu** [comment]
@tomhughes  I know the error of not connecting to the database, if I delete RAILS_ENV=production it reports a database connection error, which is what I want.

There should be some problems with the program in production.

**Comment by tomhughes** [comment]
Well that's because you haven't edited `database.yml` to specify where your databases are, as I already said.

**Comment by RanQiwu** [comment]
Even if I edit the correct database configuration, it will still report an error in the production environment, but not in the development environment.

**Comment by gravitystorm** [comment]
This is related to serving assets in production. The error message you get says that their is no `errors/not_found` template with `formats=>[:css]`, since you are requesting css files from the server and it doesn't know how to serve them to you.

In CONFIGURE.md we recommend against running `rails server` in production. Normally your application server, such as Phusion Passenger, will take care of serving static assets (like css files) in production.

If you really want to run `rails server` in production - and again, we do recommend against it - then you need to enable the serving of static assets via rails itself. [You can enable this with an environment variable](https://github.com/openstreetmap/openstreetmap-website/blob/59444581dc0cf1f140c596d518596b0e7da669ac/config/environments/production.rb#L21-L23), so the following works (and I've tested it today):

`RAILS_ENV=production RAILS_SERVE_STATIC_FILES=true bundle exec rails server`
