### ISSUE TITLE
Sprockets vs optional config files

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#2185]
In [app/assets/javascripts/osm.js.erb](https://github.com/openstreetmap/openstreetmap-website/blob/53cc1d2d11d358c171ee5beab55a3d20b79e9dab/app/assets/javascripts/osm.js.erb) we need to tell sprockets to recompile the output whenever the settings change. To do this we mark that file as depending on `config/settings.yml` and `config/settings.local.yml`.

However, this throws up two problems:

* `settings.local.yml` is supposed to be optional, but Sprockets throws an error if the file can't be found.
* The config gem also supports a [bunch of other files](https://github.com/railsconfig/config/blob/3a28b646a69c16f87d6539b4e1c4189aecb34c84/lib/config.rb#L60-L70), which should also trigger a recompile if they exist and then get changed.

I've checked through the sprockets documentation, but I can't see any obvious guidance for approaches to this situation.

Potential solutions include:

* Remove the dependency on `settings.local.yml`. This will make the 'out-of-the-box' situation better for developers, but could lead to problems later on when changes to that file are not reflected in the compiled javascript (without manual asset recompilation).
* Ask the upstream sprockets developers what they think about depending on optional files, or if they have any suggestions.
* Create an initializer which outputs the computed settings to a file, and depend on that output file instead.

**Comment by gravitystorm** [comment]
For anyone who gets `ActionView::Template::Error: couldn't find file 'settings.local.yml'` or similar when first setting up your environment, then this issue is the root cause. You need to create an empty file in `config/settings.local.yml`, for example by running:

```bash
$ touch config/settings.local.yml
```

**Comment by mmd-osm** [comment]
How about:
* Create an empty settings.local.yml file in config.rb, in case no local settings have been created
* If that doesn't work, print out an error message and exit, asking the dev to create an empty file settings.local.yml file themselves.

**Comment by mmd-osm** [comment]
I'm not seeing any error messages on Rails 8 anyone in case config/settings.local.yml is missing. Is this working as expected? Maybe we could remove the respective section in the readme file now.

**Comment by pablobm** [comment]
For a new datapoint: I cloned the repo today and can see the errors if I run the test suite without the `config/settings.local.yml` file. Eg:

```
$ docker compose run --rm web bundle exec rails test:all
[+] Creating 1/1
 ✔ Container openstreetmap-website-db-1  Running                                                                                                                                                                                       0.0s
Running 2526 tests in parallel using 8 processes
Run options: --seed 14882

# Running:

..............................................E

Error:
Messages::RepliesControllerTest#test_new:
ActionView::Template::Error: couldn't find file 'settings.local.yml'
Checked in these paths:
  /app/app/assets/config
  /app/app/assets/favicons
  /app/app/assets/images
  /app/app/assets/javascripts
  /app/app/assets/opensearch
  /app/app/assets/stylesheets
  /app/vendor/assets/iD
  /app/vendor/assets/jquery
  /app/vendor/assets/leaflet
  /usr/local/bundle/gems/teaspoon-1.4.0/app/assets/javascripts
  /usr/local/bundle/gems/teaspoon-1.4.0/app/assets/stylesheets
  /usr/local/bundle/gems/doorkeeper-5.8.2/app/assets/stylesheets
  /usr/local/bundle/gems/doorkeeper-5.8.2/vendor/assets/stylesheets
  /usr/local/bundle/gems/bootstrap_form-5.4.0/app/assets/stylesheets
  /usr/local/bundle/gems/jquery-rails-4.6.0/vendor/assets/javascripts
  /usr/local/bundle/gems/turbo-rails-2.0.16/app/assets/javascripts
  /usr/local/bundle/gems/actiontext-8.0.2/app/assets/javascripts
  /usr/local/bundle/gems/actiontext-8.0.2/app/assets/stylesheets
  /usr/local/bundle/gems/actioncable-8.0.2/app/assets/javascripts
  /usr/local/bundle/gems/activestorage-8.0.2/app/assets/javascripts
  /usr/local/bundle/gems/actionview-8.0.2/app/assets/javascripts
  /app/config
  /app/node_modules
  /usr/local/bundle/gems/popper_js-2.11.8/assets/javascripts
  /usr/local/bundle/gems/bootstrap-5.3.5/assets/stylesheets
  /usr/local/bundle/gems/bootstrap-5.3.5/assets/javascripts
  /app/test/javascripts
  /app/test/javascripts/stylesheets
  /usr/local/bundle/gems/teaspoon-mocha-2.3.3/lib/teaspoon/mocha/assets
    app/assets/javascripts/osm.js.erb:2
    app/views/layouts/_head.html.erb:4
    app/views/layouts/_head.html.erb:1
    app/views/layouts/site.html.erb:5
    app/views/layouts/site.html.erb:2
    app/views/layouts/map.html.erb:83
    config/initializers/policy_headers.rb:11:in `call'
    config/initializers/compressed_requests.rb:27:in `call'
    test/test_helper.rb:212:in `session_for'
    test/controllers/messages/replies_controller_test.rb:25:in `test_new'


bin/rails test test/controllers/messages/replies_controller_test.rb:14
```
