### ISSUE TITLE
Problem with running project in production environment

### ISSUE THREAD

**Issue by m-nouredini** [openstreetmap/openstreetmap-website#2744]
Hello everyone,
I'm trying to dockerize and run the latest version of the master branch in the production environment using Nginx and Passenger,
when I run the project in dev env using `bundle exec rails server` everything works fine,
but in production, I can see the main page and login page but some specific requests (such as signup page, history, etc.) fails with `no implicit conversion of nil into String` error, unfortunately, I'm not very familiar with ruby and rails, and I can not find the cause of this errors.
so I copied some of the stack traces below and I'll appreciate it if someone can help me with this problem.
Thanks.

```
I, [2020-08-02T10:06:08.752734 #100]  INFO -- : [0d23586c-e570-4f2a-96b0-b3b48b15cc66] Started GET "/user/new" for 172.24.0.1 at 2020-08-02 10:06:08 +0000
I, [2020-08-02T10:06:08.754915 #100]  INFO -- : [0d23586c-e570-4f2a-96b0-b3b48b15cc66] Processing by UsersController#new as HTML
I, [2020-08-02T10:06:08.762556 #100]  INFO -- : [0d23586c-e570-4f2a-96b0-b3b48b15cc66] Completed 500 Internal Server Error in 7ms (Allocations: 1690)
F, [2020-08-02T10:06:08.764425 #100] FATAL -- : [0d23586c-e570-4f2a-96b0-b3b48b15cc66]   
[0d23586c-e570-4f2a-96b0-b3b48b15cc66] TypeError (no implicit conversion of nil into String):
[0d23586c-e570-4f2a-96b0-b3b48b15cc66]   
[0d23586c-e570-4f2a-96b0-b3b48b15cc66] app/models/acl.rb:24:in `match'
[0d23586c-e570-4f2a-96b0-b3b48b15cc66] app/models/acl.rb:33:in `no_account_creation'
[0d23586c-e570-4f2a-96b0-b3b48b15cc66] app/controllers/users_controller.rb:716:in `check_signup_allowed'
[0d23586c-e570-4f2a-96b0-b3b48b15cc66] app/controllers/users_controller.rb:228:in `new'
[0d23586c-e570-4f2a-96b0-b3b48b15cc66] config/initializers/compressed_requests.rb:27:in `call'
[0d23586c-e570-4f2a-96b0-b3b48b15cc66] config/initializers/cors.rb:9:in `call'
I, [2020-08-02T10:06:08.765844 #100]  INFO -- : [0d23586c-e570-4f2a-96b0-b3b48b15cc66] Processing by ErrorsController#internal_server_error as HTML
I, [2020-08-02T10:06:08.767235 #100]  INFO -- : [0d23586c-e570-4f2a-96b0-b3b48b15cc66]   Rendering errors/internal_server_error.html.erb within layouts/error
I, [2020-08-02T10:06:08.767531 #100]  INFO -- : [0d23586c-e570-4f2a-96b0-b3b48b15cc66]   Rendered errors/internal_server_error.html.erb within layouts/error (Duration: 0.1ms | Allocations: 4)
I, [2020-08-02T10:06:08.774285 #100]  INFO -- : [0d23586c-e570-4f2a-96b0-b3b48b15cc66]   Rendered layouts/_meta.html.erb (Duration: 6.0ms | Allocations: 2602)
I, [2020-08-02T10:06:08.775209 #100]  INFO -- : [0d23586c-e570-4f2a-96b0-b3b48b15cc66] Completed 500 Internal Server Error in 9ms (Views: 8.3ms | Allocations: 3134)
```

```
I, [2020-08-02T10:07:41.734821 #5884]  INFO -- : [c50f7613-0e79-49df-9ca9-c6482fcb0399] Started GET "/history?xhr=1" for 172.24.0.1 at 2020-08-02 10:07:41 +0000
I, [2020-08-02T10:07:41.735656 #5884]  INFO -- : [c50f7613-0e79-49df-9ca9-c6482fcb0399] Processing by ChangesetsController#index as HTML
I, [2020-08-02T10:07:41.735719 #5884]  INFO -- : [c50f7613-0e79-49df-9ca9-c6482fcb0399]   Parameters: {"xhr"=>"1"}
I, [2020-08-02T10:07:41.738050 #5884]  INFO -- : [c50f7613-0e79-49df-9ca9-c6482fcb0399]   Rendering changesets/history.html.erb within layouts/xhr
I, [2020-08-02T10:07:41.738941 #5884]  INFO -- : [c50f7613-0e79-49df-9ca9-c6482fcb0399]   Rendered changesets/history.html.erb within layouts/xhr (Duration: 0.8ms | Allocations: 530)
I, [2020-08-02T10:07:41.740322 #5884]  INFO -- : [c50f7613-0e79-49df-9ca9-c6482fcb0399] Completed 200 OK in 5ms (Views: 2.0ms | Allocations: 2850)
I, [2020-08-02T10:07:41.747632 #5884]  INFO -- : [492f711b-1771-4701-bbf2-9310136319cb] Started GET "/history?list=1&bbox=-26.89453125%2C37.26530995561875%2C42.099609375%2C62.34960927573042" for 172.24.0.1 at 2020-08-02 10:07:41 +0000
I, [2020-08-02T10:07:41.749035 #5884]  INFO -- : [492f711b-1771-4701-bbf2-9310136319cb] Processing by ChangesetsController#index as */*
I, [2020-08-02T10:07:41.749135 #5884]  INFO -- : [492f711b-1771-4701-bbf2-9310136319cb]   Parameters: {"list"=>"1", "bbox"=>"-26.89453125,37.26530995561875,42.099609375,62.34960927573042"}
I, [2020-08-02T10:07:41.752653 #5884]  INFO -- : [492f711b-1771-4701-bbf2-9310136319cb] Completed 500 Internal Server Error in 3ms (Allocations: 2290)
F, [2020-08-02T10:07:41.753095 #5884] FATAL -- : [492f711b-1771-4701-bbf2-9310136319cb]   
[492f711b-1771-4701-bbf2-9310136319cb] TypeError (no implicit conversion of nil into String):
[492f711b-1771-4701-bbf2-9310136319cb]   
[492f711b-1771-4701-bbf2-9310136319cb] app/controllers/changesets_controller.rb:90:in `conditions_bbox'
[492f711b-1771-4701-bbf2-9310136319cb] app/controllers/changesets_controller.rb:54:in `index'
[492f711b-1771-4701-bbf2-9310136319cb] app/controllers/application_controller.rb:232:in `block in web_timeout'
[492f711b-1771-4701-bbf2-9310136319cb] app/controllers/application_controller.rb:231:in `web_timeout'
[492f711b-1771-4701-bbf2-9310136319cb] config/initializers/compressed_requests.rb:27:in `call'
[492f711b-1771-4701-bbf2-9310136319cb] config/initializers/cors.rb:9:in `call'
I, [2020-08-02T10:07:41.753525 #5884]  INFO -- : [492f711b-1771-4701-bbf2-9310136319cb] Processing by ErrorsController#internal_server_error as */*
I, [2020-08-02T10:07:41.753560 #5884]  INFO -- : [492f711b-1771-4701-bbf2-9310136319cb]   Parameters: {"list"=>"1", "bbox"=>"-26.89453125,37.26530995561875,42.099609375,62.34960927573042"}
I, [2020-08-02T10:07:41.754226 #5884]  INFO -- : [492f711b-1771-4701-bbf2-9310136319cb]   Rendering errors/internal_server_error.html.erb within layouts/error
I, [2020-08-02T10:07:41.754358 #5884]  INFO -- : [492f711b-1771-4701-bbf2-9310136319cb]   Rendered errors/internal_server_error.html.erb within layouts/error (Duration: 0.0ms | Allocations: 4)
I, [2020-08-02T10:07:41.756218 #5884]  INFO -- : [492f711b-1771-4701-bbf2-9310136319cb]   Rendered layouts/_meta.html.erb (Duration: 1.4ms | Allocations: 2612)
I, [2020-08-02T10:07:41.756588 #5884]  INFO -- : [492f711b-1771-4701-bbf2-9310136319cb] Completed 500 Internal Server Error in 3ms (Views: 2.7ms | Allocations: 3441)

```

**Comment by tomhughes** [comment]
Well those appear to be two different. although possibly related, issues.

The first looks like whatever web/application server you are using is not providing the IP address of the client so `request.remote_ip` is not populated.

The second looks like the `bbox` query parameter is not being provided or something, although it looks like we have the key but it has no value?

In general it looks like a problem with whatever tools you are using to interface the rails app to the rest of the world - the request details just aren't making it to rails properly.

**Comment by m-nouredini** [comment]
It seems strange but I found that I got those errors because the production db config is not set correctly, I wanted to use environment variables to pass the db config to the app, and to do that I used the below database.yml:

```
production:
  adapter: postgresql
  database: <%= ENV['OSM_DB'] %>
  username: <%= ENV['OSM_DB_USER'] %>
  password: <%= ENV['OSM_DB_PASSWORD'] %>
  host: <%= ENV['OSM_DB_HOST'] %>
  encoding: utf8
```

after hard coding those variables in the config file, the errors are gone and everything seems to work fine
