### ISSUE TITLE
Create a rake task for populating the database

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#282]
Currently the installation notes spend about 90 lines explaining how to populate the database from an extract. A substantial portion of this concerns osmosis options and resetting sequences.

This could be simplified by creating a rake task that calls osmosis with the configured database parameters and takes care of the sequences.

**Comment by hanchao** [comment]
@danstowell Error occurred. Any help?

[hanchao07@dx-wmarch-map-routing01 ~]$ ./osmosis/bin/osmosis --truncate-apidb host="waimai-pgsql-wmmapdata01-write.vip.sankuai.com" database="wmgis" user="wmgis_rw" password="3ab8CPjB0C1mx6q7fdsuOuLkp" validateSchemaVersion="no"
九月 19, 2016 5:14:58 下午 org.openstreetmap.osmosis.core.Osmosis run
信息: Osmosis Version 0.45
九月 19, 2016 5:14:58 下午 org.openstreetmap.osmosis.core.Osmosis run
信息: Preparing pipeline.
九月 19, 2016 5:14:58 下午 org.openstreetmap.osmosis.core.Osmosis run
信息: Launching pipeline execution.
九月 19, 2016 5:14:58 下午 org.openstreetmap.osmosis.core.Osmosis run
信息: Pipeline executing, waiting for completion.
九月 19, 2016 5:14:59 下午 org.openstreetmap.osmosis.core.Osmosis run
信息: Pipeline complete.
九月 19, 2016 5:14:59 下午 org.openstreetmap.osmosis.core.Osmosis run
信息: Total execution time: 674 milliseconds.

[hanchao07@dx-wmarch-map-routing01 ~]$ ./osmosis/bin/osmosis --read-pbf file=china-latest.osm.pbf --write-apidb host="waimai-pgsql-wmmapdata01-write.vip.sankuai.com" database="wmgis" user="wmgis_rw" password="****" validateSchemaVersion="no"
九月 19, 2016 5:15:11 下午 org.openstreetmap.osmosis.core.Osmosis run
信息: Osmosis Version 0.45
九月 19, 2016 5:15:11 下午 org.openstreetmap.osmosis.core.Osmosis run
信息: Preparing pipeline.
九月 19, 2016 5:15:11 下午 org.openstreetmap.osmosis.core.Osmosis run
信息: Launching pipeline execution.
九月 19, 2016 5:15:11 下午 org.openstreetmap.osmosis.core.Osmosis run
信息: Pipeline executing, waiting for completion.
九月 19, 2016 5:16:18 下午 org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
严重: Thread for task 1-read-pbf failed
org.openstreetmap.osmosis.core.OsmosisRuntimeException: Unable to insert user with id 3642735 into the database.
       	at org.openstreetmap.osmosis.apidb.v0_6.impl.UserManager.insertUser(UserManager.java:143)
       	at org.openstreetmap.osmosis.apidb.v0_6.impl.UserManager.addOrUpdateUser(UserManager.java:191)
       	at org.openstreetmap.osmosis.apidb.v0_6.ApidbWriter.process(ApidbWriter.java:1098)
       	at crosby.binary.osmosis.OsmosisBinaryParser.parseDense(OsmosisBinaryParser.java:138)
       	at org.openstreetmap.osmosis.osmbinary.BinaryParser.parse(BinaryParser.java:124)
       	at org.openstreetmap.osmosis.osmbinary.BinaryParser.handleBlock(BinaryParser.java:68)
       	at org.openstreetmap.osmosis.osmbinary.file.FileBlock.process(FileBlock.java:135)
       	at org.openstreetmap.osmosis.osmbinary.file.BlockInputStream.process(BlockInputStream.java:34)
       	at crosby.binary.osmosis.OsmosisReader.run(OsmosisReader.java:45)
       	at java.lang.Thread.run(Thread.java:745)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_display_name_idx"
  详细：Key (display_name)=(Nodes&Roads) already exists.
       	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2103)
       	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1836)
       	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
       	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:512)
       	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:388)
       	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:334)
       	at org.openstreetmap.osmosis.apidb.v0_6.impl.UserManager.insertUser(UserManager.java:140)
       	... 9 more

九月 19, 2016 5:16:18 下午 org.openstreetmap.osmosis.core.Osmosis main
严重: Execution aborted.
org.openstreetmap.osmosis.core.OsmosisRuntimeException: One or more tasks failed.
       	at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.waitForCompletion(Pipeline.java:146)
       	at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:92)
       	at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
       	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.lang.reflect.Method.invoke(Method.java:606)
       	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
       	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
       	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
       	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
       	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)

**Comment by mojodna** [comment]
@hanchao this is the root cause: https://github.com/drolbr/Overpass-API/issues/257 (even if it didn't come from Overpass).

Here's a shell script that will remap user IDs after the extract has been converted to XML: https://github.com/AmericanRedCross/posm-replay-tool/blob/c25d8e1f62af44e0664190723eba51eef7b93adc/remap-userid.sh

My notes in https://github.com/AmericanRedCross/posm-replay-tool/blob/28deac4193859b71af34d845f013194a37871870/LOCAL.md#initialization explain what's going on and steps to fix it (locally).

**Comment by hanchao** [comment]
@mojodna Thanks.

3642735  1708958 have the same name (Nodes&Roads)
```
<node id="1546831475" version="2" timestamp="2016-08-31T17:30:44Z" uid="3642735" user="Nodes&amp;Roads" changeset="41831739" lat="34.6455964" lon="110.3129604"/>
  <node id="1582851239" version="3" timestamp="2016-02-18T20:41:39Z" uid="1708958" user="Nodes&amp;Roads" changeset="37297109" lat="38.9261979" lon="113.8765729"/>
```

https://www.openstreetmap.org/api/0.6/node/1582851239
```
<node id="1582851239" visible="true" version="3" changeset="37297109" timestamp="2016-02-18T20:41:39Z" user="georhoko" uid="1708958" lat="38.9261979" lon="113.8765729"/>
```

The name is not updated in china-latest.osm.pbf

**Comment by maxdeepfield** [comment]
I successfully installed The Rails Port then imported data with osmosis, configured iD to this local server and now able to edit data.

Where openstreetmap-website stores saved data? I made changes, saved them, even restarted server, but  I cant just export my changes from apidb to .osm file

**Comment by tomhughes** [comment]
@maxdeepfield Your comment has nothing to do with this thread and in any case is not appropriate here - please ask on the dev or rails-dev mailing lists, or on #osm-dev on IRC if you need help using the code.

**Comment by maxdeepfield** [comment]
reading "about 90 lines explaining how to populate the database" is not very hard task if these lines exists and will work. any progress on this?

**Comment by maxdeepfield** [comment]
Anyway, osmosis --write-apidb line works fine with geofabrik extracts, after import I can see and edit data, then get the result (complete dump?) via osmosis --read-apidb-current, what with --write-pbf gives new dataset. 

If processes done without errors - do I need to care about something?

**Comment by prusswan** [comment]
Managed to import my region extract from geofabrik after resolving various data issues, which can be resolved with some database knowledge and background understanding (e.g. data extracts need to satisfy some integrity conditions) of these issues #1988, #2449, #2543

Anyway, I feel the real issue now may be that users don't realize "populating the database from an OSM extract" requires the data to be imported to meet certain conditions, for the step to "just work" (and possibly for the proposed rake task to run without getting tripped). Would it help to have another section covering the kind of data preparation which may be required?

**Comment by victorovento** [comment]
Well I think this script will be never written.

**Comment by rkoeze** [comment]
@gravitystorm, are you thinking this rake task would rely on something like Osmosis and use `clipIncompleteEntities=true` or something similar? I believe Osmium also allows for referentially complete extractions. There's probably some version of this where the rake task takes arguments that would allow the operator to define the area they wanted to import.

For what it's worth, I didn't find the [directions to populate the database in the Configure.md docs](https://github.com/openstreetmap/openstreetmap-website/blob/master/CONFIGURE.md#populating-the-database) too cumbersome. So, one alternative might be to flesh out the docs with options for referentially complete imports instead of having a single rake task.

**Comment by rkoeze** [comment]
@gravitystorm it seems like some combination of osmosis with the `clipIncompleteEntities=true` argument and then a bunch of `ALTER SEQUENCE changesets_id_seq RESTART WITH n;` sql commands might work here. Are you still interested in this rake task being written?

I suppose one disadvantage here is that it's just another thing to maintain (for example every time a new sequence is introduced this command will have to be updated). An alternative might be updating the the docs with general instructions for importing referentially complete entities but then let developers do the work themselves.

If you do still think this would be worthwhile I'd be happy to put up a draft PR for feedback. Thanks!

**Comment by rkoeze** [comment]
@tomhughes just wondering if you have any feedback on my comment above. Thanks in advance for your time.
