### ISSUE TITLE
Unable to send email in response to personal message

### ISSUE THREAD

**Issue by Nakaner** [openstreetmap/openstreetmap-website#2895]
I tried to respond to a personal message on openstreetmap.org (not a changeset comment) by email but it failed twice today:

```
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  m-897553-60d7f3@messages.openstreetmap.org
    local delivery failed

The following text was generated during the delivery attempt:

------ m-897553-60d7f3@messages.openstreetmap.org ------

WARN: advpng none at /usr/bin/advpng (== none) is of unknown version
/var/lib/gems/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `block in load_missing_constant': uninitialized constant Notifier (NameError)
	from /var/lib/gems/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:9:in `without_bootsnap_cache'
	from /var/lib/gems/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `rescue in load_missing_constant'
	from /var/lib/gems/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
	from /srv/www.openstreetmap.org/rails/script/deliver-message:36:in `<main>'
/var/lib/gems/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `block in load_missing_constant': uninitialized constant Notifier (NameError)
	from /var/lib/gems/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
	from /var/lib/gems/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `load_missing_constant'
	from /srv/www.openstreetmap.org/rails/script/deliver-message:36:in `<main>'


Reporting-MTA: dns; spike-06.openstreetmap.org

Action: failed
Final-Recipient: rfc822;m-897553-60d7f3@messages.openstreetmap.org
Status: 5.0.0
```

Date: today 11:36 and 11:40 UTC

**Comment by gravitystorm** [comment]
I've created a pull request to fix this; it will need to be merged and then deployed.
