### ISSUE TITLE
GPX import: stacktrace

### ISSUE THREAD

**Issue by richlv** [openstreetmap/openstreetmap-website#3007]
Attempted to upload a few older files, and one failed with a big trace, all in one line. This might have happened because the trace was all on one spot.

 It looks like your GPX file 20120519.gpx with the description 2012-missed-6 and no tags failed to import. Here is the error:
```
NaN 
/var/lib/gems/2.7.0/gems/gd2-ffij-0.4.0/lib/gd2/canvas.rb:44:in `to_i' 
/var/lib/gems/2.7.0/gems/gd2-ffij-0.4.0/lib/gd2/canvas.rb:44:in `draw' 
/var/lib/gems/2.7.0/gems/gd2-ffij-0.4.0/lib/gd2/canvas.rb:313:in `line' 
/srv/www.openstreetmap.org/rails/lib/gpx.rb:107:in `block (3 levels) in picture' 
/srv/www.openstreetmap.org/rails/lib/gpx.rb:30:in `parse_file' 
/srv/www.openstreetmap.org/rails/lib/gpx.rb:58:in `rescue in points' 
/srv/www.openstreetmap.org/rails/lib/gpx.rb:46:in `points' 
/srv/www.openstreetmap.org/rails/lib/gpx.rb:95:in `each_with_index' 
/srv/www.openstreetmap.org/rails/lib/gpx.rb:95:in `block (2 levels) in picture' 
/var/lib/gems/2.7.0/gems/gd2-ffij-0.4.0/lib/gd2/image.rb:440:in `draw' 
/srv/www.openstreetmap.org/rails/lib/gpx.rb:85:in `block in picture' 
/var/lib/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/core_ext/range/each.rb:9:in `each'
/var/lib/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/core_ext/range/each.rb:9:in `each'
/srv/www.openstreetmap.org/rails/lib/gpx.rb:74:in `picture' 
/srv/www.openstreetmap.org/rails/app/models/trace.rb:296:in `import' 
/srv/www.openstreetmap.org/rails/app/jobs/trace_importer_job.rb:5:in `perform' 
/var/lib/gems/2.7.0/gems/activejob-6.0.3.4/lib/active_job/execution.rb:40:in `block in perform_now' 
/var/lib/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:112:in `block in run_callbacks' 
/var/lib/gems/2.7.0/gems/i18n-1.8.5/lib/i18n.rb:313:in `with_locale' 
/var/lib/gems/2.7.0/gems/activejob-6.0.3.4/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>' 
/var/lib/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:121:in `instance_exec' 
/var/lib/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:121:in `block in run_callbacks' 
/var/lib/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/core_ext/time/zones.rb:66:in `use_zone' 
/var/lib/gems/2.7.0/gems/activejob-6.0.3.4/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>' 
/var/lib/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:121:in `instance_exec' 
...
```

**Comment by richlv** [comment]
Couldn't attach a GPX here, one that allows to reproduce this: https://drive.google.com/file/d/1l35anHjGP3qfytHguTEnM5P2pCGA5FJ8/view?usp=sharing .

**Comment by gravitystorm** [comment]
(I added some newlines to the trace, and remove the surprisingly large amount that was just actionjob stuff)

**Comment by mmd-osm** [comment]
Is it expected that the gpx file has all points at lat="56.953554" lon="24.220943"? This seems highly unusual for any gpx trace to me.

**Comment by richlv** [comment]
Yes and no - this can happen, but it obviously is not a useful trace for OSM.
In such a case I'd expect a short error message, explaining why the trace failed, instead of the stacktrace.

**Comment by mmd-osm** [comment]
Identical min/max_lax/mon in gpx.rb, line 70:

      proj = OSM::Mercator.new(min_lat, min_lon, max_lat, max_lon, width, height)

followed by lines 96+97

            px = proj.x(p.longitude)
            py = proj.y(p.latitude)

triggers a division by zero in osm.rb lines 382-388:

```
    def y(lat)
      @height - ((ysheet(lat) - @ty) / (@by - @ty) * @height)
    end

    def x(lon)
      ((xsheet(lon) - @tx) / (@bx - @tx) * @width)
    end
```

**Comment by richlv** [comment]
Yay, thank you :)
