### ISSUE TITLE
API endpoints sporadically rejecting connections

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/openstreetmap-website#3490]
### URL

https://api.openstreetmap.org/api/0.6/changeset/create

### How to reproduce the issue?

Sporadically the cgimap backed API endpoints seem to be rejecting client connections.

### Screenshot(s) or anything else?

Example rejected connection on JOSM upload:

```
2022-02-28 18:47:13.388 INFO: PUT https://api.openstreetmap.org/api/0.6/changeset/create (229 B) ...
2022-02-28 18:47:13.391 INFO: PUT https://api.openstreetmap.org/api/0.6/changeset/create -> !!! (1 ms)
2022-02-28 18:47:13.391 WARNING: java.net.SocketException: Unexpected end of file from server. Cause: java.net.SocketException: Unexpected end of file from server
java.net.SocketException: Unexpected end of file from server
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at org.openstreetmap.josm.tools.Http1Client$1.getResponseCode(Http1Client.java:94)
	at org.openstreetmap.josm.tools.HttpClient.connect(HttpClient.java:152)
	at org.openstreetmap.josm.tools.HttpClient.connect(HttpClient.java:124)
	at org.openstreetmap.josm.io.OsmApi.sendRequest(OsmApi.java:729)
	at org.openstreetmap.josm.io.OsmApi.sendRequest(OsmApi.java:673)
	at org.openstreetmap.josm.io.OsmApi.sendRequest(OsmApi.java:668)
	at org.openstreetmap.josm.io.OsmApi.sendPutRequest(OsmApi.java:663)
	at org.openstreetmap.josm.io.OsmApi.openChangeset(OsmApi.java:463)
	at org.openstreetmap.josm.io.OsmServerWriter.uploadOsm(OsmServerWriter.java:202)
	at org.openstreetmap.josm.gui.io.UploadPrimitivesTask.realRun(UploadPrimitivesTask.java:266)
	at org.openstreetmap.josm.gui.io.AsynchronousUploadPrimitivesTask.realRun(AsynchronousUploadPrimitivesTask.java:129)
	at org.openstreetmap.josm.gui.PleaseWaitRunnable.doRealRun(PleaseWaitRunnable.java:94)
	at org.openstreetmap.josm.gui.PleaseWaitRunnable.run(PleaseWaitRunnable.java:142)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.SocketException: Unexpected end of file from server
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:866)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1615)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3135)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getHeaderField(HttpsURLConnectionImpl.java:295)
	at org.openstreetmap.josm.tools.Http1Client$1.getResponseVersion(Http1Client.java:85)
	... 15 more

2022-02-28 18:47:13.392 INFO: Message notifier active (checks every 60 minutes)
2022-02-28 18:47:13.547 SEVERE: org.openstreetmap.josm.io.OsmTransferException: java.net.SocketException: Unexpected end of file from server. Cause: java.net.SocketException: Unexpected end of file from server. Cause: java.net.SocketException: Unexpected end of file from server
org.openstreetmap.josm.io.OsmTransferException: java.net.SocketException: Unexpected end of file from server
	at org.openstreetmap.josm.io.OsmApi.sendRequest(OsmApi.java:777)
	at org.openstreetmap.josm.io.OsmApi.sendRequest(OsmApi.java:673)
	at org.openstreetmap.josm.io.OsmApi.sendRequest(OsmApi.java:668)
	at org.openstreetmap.josm.io.OsmApi.sendPutRequest(OsmApi.java:663)
	at org.openstreetmap.josm.io.OsmApi.openChangeset(OsmApi.java:463)
	at org.openstreetmap.josm.io.OsmServerWriter.uploadOsm(OsmServerWriter.java:202)
	at org.openstreetmap.josm.gui.io.UploadPrimitivesTask.realRun(UploadPrimitivesTask.java:266)
	at org.openstreetmap.josm.gui.io.AsynchronousUploadPrimitivesTask.realRun(AsynchronousUploadPrimitivesTask.java:129)
	at org.openstreetmap.josm.gui.PleaseWaitRunnable.doRealRun(PleaseWaitRunnable.java:94)
	at org.openstreetmap.josm.gui.PleaseWaitRunnable.run(PleaseWaitRunnable.java:142)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.SocketException: Unexpected end of file from server
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at org.openstreetmap.josm.tools.Http1Client$1.getResponseCode(Http1Client.java:94)
	at org.openstreetmap.josm.tools.HttpClient.connect(HttpClient.java:152)
	at org.openstreetmap.josm.tools.HttpClient.connect(HttpClient.java:124)
	at org.openstreetmap.josm.io.OsmApi.sendRequest(OsmApi.java:729)
	... 12 more
Caused by: java.net.SocketException: Unexpected end of file from server
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:866)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1615)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3135)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getHeaderField(HttpsURLConnectionImpl.java:295)
	at org.openstreetmap.josm.tools.Http1Client$1.getResponseVersion(Http1Client.java:85)
	... 15 more

2022-02-28 18:47:13.554 SEVERE: Network exception - <html>Failed to open a connection to the remote server<br>'https://api.openstreetmap.org/api/0.6/'.<br>Please check your internet connection.</html> 
```

**Comment by Firefishy** [comment]
I have occasionally over the last few weeks had connections being rejected from the API. Very sporadic. Fails a few retries and then starts working again.

**Comment by simonpoole** [comment]
Could it be the same sympton as discussed here https://forum.openstreetmap.org/viewtopic.php?id=74624 ?

**Comment by mmd-osm** [comment]
Changeset create isn't being handled by cgimap...

**Comment by Firefishy** [comment]
> Changeset create endpoint isn't being handled by cgimap but the Rails port

Updated initial description now.

**Comment by mmd-osm** [comment]
btw: here's a similar report that was created as a result of the forum discussion: https://josm.openstreetmap.de/ticket/21806
It's the same "Unexpected end of file from server.", but it lacks pretty much all detail about the endpoint.

**Comment by simonpoole** [comment]
@mmd-osm it could very well be JOSM specific given there doesn't seem to be any reports of similar errors with other editors (and I suspect given that the changeset and upload numbers are much much higher than with JOSM we should be seeing other reports).

**Comment by Firefishy** [comment]
JOSM, MacOS, IPv4 with IPv6 disabled is the client I received the errors on.

**Comment by flohoff** [comment]
I was observing it also (As i reported it on twitter) and i fail to reproduce it now. The change is that i think yesterday i upgraded josm to josm-latest-18382.jar (from i think josm-latest-18368.jar) - Running with --debug too now and a tcpdump in background. I had a tcpdump of a broken session but i cant find it anymore.
