### ISSUE TITLE
Mismatch between configuration and actual values for setting

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#3509]
I've been doing some work today and came across a strange bug where the configuration in our initializers is not being properly applied. Specifically, we already set `action_controller.raise_on_open_redirects` to true https://github.com/openstreetmap/openstreetmap-website/blob/b01ffa427e6adc17f7aa4f0eb12043cf2c82dcec/config/initializers/new_framework_defaults_7_0.rb#L76

However, a simple patch shows that this not being transferred to the class properly:

```diff
diff --git a/app/controllers/application_controller.rb b/app/controllers/application_controller.rb
index 1d6865405..af3ba9a59 100644
--- a/app/controllers/application_controller.rb
+++ b/app/controllers/application_controller.rb
@@ -75,6 +75,9 @@ class ApplicationController < ActionController::Base
     if request.cookies["_osm_session"].to_s == ""
       if params[:cookie_test].nil?
         session[:cookie_test] = true
+        puts "# Raise on open redirects"
+        puts "Configuration: #{Rails.application.config.action_controller.raise_on_open_redirects}"
+        puts "Actual value:  #{ActionController::Base.raise_on_open_redirects}"
         redirect_to params.to_unsafe_h.merge(:only_path => true, :cookie_test => "true")
         false
       else
```

```bash
$ bundle exec rails test test/controllers/sessions_controller_test.rb
...
# Raise on open redirects
Configuration: true
Actual value:  false
```

If I change the application `load_defaults` to 7.0:

```diff
diff --git a/config/application.rb b/config/application.rb
index 10a2372db..b51d8e213 100644
--- a/config/application.rb
+++ b/config/application.rb
@@ -21,7 +21,7 @@ Bundler.require(*Rails.groups)
 module OpenStreetMap
   class Application < Rails::Application
     # Initialize configuration defaults for originally generated Rails version.
-    config.load_defaults 6.1
+    config.load_defaults 7.0
 
```

Then I get the expected result:
```bash
$ bundle exec rails test test/controllers/sessions_controller_test.rb
...
# Raise on open redirects
Configuration: true
Actual value:  true
```

I'm not sure what's going on here, and I'm concerned that other settings in the `new_framework_defaults_7_0.rb` file, or other initializers, might also not be applied properly.

(I'm aware that Tom has already got a patch into upstream rails relating to `only_path`, but this configuration mismatch is a separate problem).

**Comment by tomhughes** [comment]
Yes I'm aware of this problem already and I assume it's a rails bug given that initializer is straight from upstream rails.

I discovered it when I tried to switch to the 7.0 defaults and get rid of the initializer which is also when I discovered the other upstream bug and raised it.

I haven't as yet attempted to diagnose this one but I assume something in rails is acting on that value before the initializer is run.

**Comment by gravitystorm** [comment]
I've tried to reproduce this in order to report it upstream, but as far as I can tell there's no problem with a fresh rails app (see https://github.com/gravitystorm/rails-settings-bug/commit/f33c9e1228e89a4b0b558627400c77abfeb51278 - the repo is just `bundle exec rails new` followed by this patch). Maybe I've made a mistake with this attempted repro though, always a possibility.

I've also tried rearranging our initializers to put the framework defaults first (`config/01_new_framework_defaults_7_0.rb`) but that didn't solve it either. So I agree that something must be triggering `ActionController::Base` to load early, but I'm not yet sure what that might be.

**Comment by gravitystorm** [comment]
Some binary-search through our gems suggests it's the `oauth-plugin` that might be causing this, and a [quick read of the code](https://github.com/pelle/oauth-plugin/blob/master/lib/oauth-plugin.rb) suggests it might be calling ActionController::Base directly during the initialization process instead of using [Lazy Load hooks](https://edgeapi.rubyonrails.org/classes/ActiveSupport/LazyLoadHooks.html)

**Comment by tomhughes** [comment]
Yes this is the trace of it getting loaded:

```
/usr/local/share/gems/ruby/3.0.0/gems/actionpack-7.0.2.3/lib/action_controller/metal/redirecting.rb:13:in `block in <module:Redirecting>': ActionController (RuntimeError)
	from /usr/local/share/gems/ruby/3.0.0/gems/activesupport-7.0.2.3/lib/active_support/concern.rb:136:in `class_eval'
	from /usr/local/share/gems/ruby/3.0.0/gems/activesupport-7.0.2.3/lib/active_support/concern.rb:136:in `append_features'
	from /usr/local/share/gems/ruby/3.0.0/gems/actionpack-7.0.2.3/lib/action_controller/base.rb:255:in `include'
	from /usr/local/share/gems/ruby/3.0.0/gems/actionpack-7.0.2.3/lib/action_controller/base.rb:255:in `block in <class:Base>'
	from /usr/local/share/gems/ruby/3.0.0/gems/actionpack-7.0.2.3/lib/action_controller/base.rb:254:in `each'
	from /usr/local/share/gems/ruby/3.0.0/gems/actionpack-7.0.2.3/lib/action_controller/base.rb:254:in `<class:Base>'
	from /usr/local/share/gems/ruby/3.0.0/gems/actionpack-7.0.2.3/lib/action_controller/base.rb:166:in `<module:ActionController>'
	from /usr/local/share/gems/ruby/3.0.0/gems/actionpack-7.0.2.3/lib/action_controller/base.rb:7:in `<main>'
	from /usr/local/share/gems/ruby/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /usr/local/share/gems/ruby/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /usr/local/share/gems/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /usr/local/share/gems/ruby/3.0.0/gems/oauth-plugin-0.5.1/lib/oauth-plugin.rb:19:in `block in <class:OAuthRailtie>'
	from /usr/local/share/gems/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/initializable.rb:32:in `instance_exec'
	from /usr/local/share/gems/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/initializable.rb:32:in `run'
	from /usr/local/share/gems/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/share/ruby/tsort.rb:228:in `block in tsort_each'
	from /usr/share/ruby/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/share/ruby/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/share/ruby/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/share/ruby/tsort.rb:347:in `each'
	from /usr/share/ruby/tsort.rb:347:in `call'
	from /usr/share/ruby/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/share/ruby/tsort.rb:226:in `tsort_each'
	from /usr/share/ruby/tsort.rb:205:in `tsort_each'
	from /usr/local/share/gems/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/initializable.rb:60:in `run_initializers'
	from /usr/local/share/gems/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/application.rb:372:in `initialize!'
	from /home/tom/src/osm/rails/config/environment.rb:5:in `<main>'
```

which as you say comes from `oauth-plugin` specifically from this code:


```ruby
if Rails::VERSION::MAJOR >= 3
  module OAuth
    module Plugin
      class OAuthRailtie < Rails::Railtie
        initializer "oauth-plugin.configure_rails_initialization" do |app|
          ActionController::Base.send :include, OAuth::Controllers::ApplicationControllerMethods
        end
      end
    end
  end
end
```

which causes `ActionController::Base` to autoload when then initialiser runs.

What I'm not sure about is how easy it is to monkey patch that...

**Comment by mmd-osm** [comment]
IIRC, oauth-plugin is used for OAuth 1.0* only.  Rather than doing some monkey patching we could remove all related code.

**Comment by gravitystorm** [comment]
The `oauth-plugin` gem was removed in #5058. 

I've confirmed today that open redirects cause an exception to be raised, and that the current version of the setting (`action_on_open_redirect`) is set to `:raise` in both the config and on the class.
