### ISSUE TITLE
Sprockets::FileNotFound in Site#index leaflet.locatecontrol/src/L.Control.Locate

### ISSUE THREAD

**Issue by Legolash2o** [openstreetmap/openstreetmap-website#3743]
I've done a fresh clone as per the instructions below on a Ubuntu VM 20.04.5 LTS. The website starts but when I browse to the server, I receive an error about a missing leaflet file.

https://github.com/openstreetmap/openstreetmap-website/blob/master/INSTALL.md

Have I missed something obvious?

Sprockets::FileNotFound in Site#index
Showing /home/azureuser/openstreetmap-website/app/views/layouts/map.html.erb where line #2 raised:

couldn't find file 'leaflet.locatecontrol/src/L.Control.Locate' with type 'application/javascript'
Checked in these paths: 
  /home/azureuser/openstreetmap-website/app/assets/config
  /home/azureuser/openstreetmap-website/app/assets/favicons
  /home/azureuser/openstreetmap-website/app/assets/images
  /home/azureuser/openstreetmap-website/app/assets/javascripts
  /home/azureuser/openstreetmap-website/app/assets/opensearch
  /home/azureuser/openstreetmap-website/app/assets/stylesheets
  /home/azureuser/openstreetmap-website/vendor/assets/iD
  /home/azureuser/openstreetmap-website/vendor/assets/jquery
  /home/azureuser/openstreetmap-website/vendor/assets/leaflet
  /home/azureuser/openstreetmap-website/vendor/assets/polyfill
  /var/lib/gems/2.7.0/gems/doorkeeper-5.6.0/app/assets/stylesheets
  /var/lib/gems/2.7.0/gems/doorkeeper-5.6.0/vendor/assets/stylesheets
  /var/lib/gems/2.7.0/gems/i18n-js-3.9.2/app/assets/javascripts
  /var/lib/gems/2.7.0/gems/bootstrap_form-5.1.0/app/assets/stylesheets
  /var/lib/gems/2.7.0/gems/jquery-rails-4.5.0/vendor/assets/javascripts
  /var/lib/gems/2.7.0/gems/actiontext-7.0.4/app/assets/javascripts
  /var/lib/gems/2.7.0/gems/actiontext-7.0.4/app/assets/stylesheets
  /var/lib/gems/2.7.0/gems/actioncable-7.0.4/app/assets/javascripts
  /var/lib/gems/2.7.0/gems/activestorage-7.0.4/app/assets/javascripts
  /var/lib/gems/2.7.0/gems/actionview-7.0.4/lib/assets/compiled
  /home/azureuser/openstreetmap-website/config
  /home/azureuser/openstreetmap-website/node_modules
  /var/lib/gems/2.7.0/gems/popper_js-2.11.6/assets/javascripts
  /var/lib/gems/2.7.0/gems/bootstrap-5.1.3/assets/stylesheets
  /var/lib/gems/2.7.0/gems/bootstrap-5.1.3/assets/javascripts
Extracted source (around line #4):
2
3
4
5
6
7
              
//= require leaflet.sidebar
//= require leaflet.sidebar-pane
//= require leaflet.locatecontrol/src/L.Control.Locate
//= require leaflet.layers
//= require leaflet.key
//= require leaflet.note

Rails.root: /home/azureuser/openstreetmap-website

Application Trace | Framework Trace | Full Trace
app/assets/javascripts/index.js:4
app/views/layouts/map.html.erb:2
app/views/layouts/map.html.erb:1
app/controllers/application_controller.rb:334:in `better_errors_allow_inline'
config/initializers/compressed_requests.rb:27:in `call'
config/initializers/cors.rb:9:in `call'

![image](https://user-images.githubusercontent.com/34819291/194715051-d20002c4-4892-4588-a294-c5bf8407c36d.png)

**Comment by Legolash2o** [comment]
Seems like I didn't run 'npm install' whilst in the openstreetmap-website directory
