### ISSUE TITLE
bundle exec eslint error

### ISSUE THREAD

**Issue by amandasaurus** [openstreetmap/openstreetmap-website#3946]
### How to reproduce the issue?

Currently [guide on contributioning](https://github.com/openstreetmap/openstreetmap-website/blob/87657108f6bd2a4afa41760dff1947a8349b28f8/CONTRIBUTING.md) says run `bundle exec rails eslint`.

However when I do that, I get the following error message:

```bash
$ docker-compose run --rm web bundle exec rails eslint
[+] Running 1/0
 ⠿ Container openstreetmap-website-db-1  Running                                                     0.0s
/usr/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/var/lib/gems/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
/usr/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/var/lib/gems/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:214: warning: previous definition of BUFSIZE was here
/usr/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/var/lib/gems/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:541: warning: previous definition of Socket was here
pngcrush worker: `pngcrush` not found; please provide proper binary or disable this worker (--no-pngcrush argument or `:pngcrush => false` through options)
advpng worker: `advpng` not found; please provide proper binary or disable this worker (--no-advpng argument or `:advpng => false` through options)
optipng worker: `optipng` not found; please provide proper binary or disable this worker (--no-optipng argument or `:optipng => false` through options)
pngquant worker: `pngquant` not found; please provide proper binary or disable this worker (--no-pngquant argument or `:pngquant => false` through options)
jhead worker: `jhead` not found, `jpegtran` not found; please provide proper binary or disable this worker (--no-jhead argument or `:jhead => false` through options)
jpegoptim worker: `jpegoptim` not found; please provide proper binary or disable this worker (--no-jpegoptim argument or `:jpegoptim => false` through options)
jpegtran worker: `jpegtran` not found; please provide proper binary or disable this worker (--no-jpegtran argument or `:jpegtran => false` through options)
gifsicle worker: `gifsicle` not found; please provide proper binary or disable this worker (--no-gifsicle argument or `:gifsicle => false` through options)
svgo worker: `svgo` not found; please provide proper binary or disable this worker (--no-svgo argument or `:svgo => false` through options)
yarn run v1.22.4
$ /app/node_modules/.bin/eslint -c /app/config/eslint.json /app/app/assets/config/manifest.js /app/app/assets/javascripts/application.js /app/app/assets/javascripts/bs-custom-file-input-init.js /app/app/assets/javascripts/diary_entry.js /app/app/assets/javascripts/fixthemap.js /app/app/assets/javascripts/id.js /app/app/assets/javascripts/index/browse.js /app/app/assets/javascripts/index/changeset.js /app/app/assets/javascripts/index/contextmenu.js /app/app/assets/javascripts/index/directions/fossgis_osrm.js /app/app/assets/javascripts/index/directions/fossgis_valhalla.js /app/app/assets/javascripts/index/directions/graphhopper.js /app/app/assets/javascripts/index/directions.js /app/app/assets/javascripts/index/export.js /app/app/assets/javascripts/index/history.js /app/app/assets/javascripts/index/new_note.js /app/app/assets/javascripts/index/note.js /app/app/assets/javascripts/index/notes.js /app/app/assets/javascripts/index/query.js /app/app/assets/javascripts/index/search.js /app/app/assets/javascripts/index.js /app/app/assets/javascripts/leaflet.key.js /app/app/assets/javascripts/leaflet.layers.js /app/app/assets/javascripts/leaflet.locate.js /app/app/assets/javascripts/leaflet.map.js /app/app/assets/javascripts/leaflet.note.js /app/app/assets/javascripts/leaflet.query.js /app/app/assets/javascripts/leaflet.share.js /app/app/assets/javascripts/leaflet.sidebar-pane.js /app/app/assets/javascripts/leaflet.sidebar.js /app/app/assets/javascripts/leaflet.zoom.js /app/app/assets/javascripts/login.js /app/app/assets/javascripts/matomo.js /app/app/assets/javascripts/messages.js /app/app/assets/javascripts/oauth.js /app/app/assets/javascripts/richtext.js /app/app/assets/javascripts/router.js /app/app/assets/javascripts/user.js /app/app/assets/javascripts/welcome.js

Oops! Something went wrong! :(

ESLint: 8.34.0

TypeError: Module.createRequire is not a function
    at Object.<anonymous> (/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2383:26)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/app/node_modules/eslint/lib/cli-engine/cli-engine.js:33:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by AntonKhorev** [comment]
I never had eslint working as described in the docs here. I run this instead:

    eslint -c config/eslint.json app/assets/javascripts/*.js app/assets/javascripts/index

**Comment by tomhughes** [comment]
Works fine for me - must be a docker issue.

As the instructions are to run "bundle exec rails eslint" not "some-docker-bollocks bundle exec rails eslint" there doesn't seem to be any evidence the instructions don't work.

**Comment by gravitystorm** [comment]
> Works fine for me - must be a docker issue.

No, it's not a Docker issue. I mentioned this previously in the final paragraph [of this comment](https://github.com/openstreetmap/openstreetmap-website/issues/3579#issuecomment-1371453162) - the version of eslint that we use requires nodejs 12+, but Ubuntu 20.04 ships with node 10. We tend not to notice since most developers (including me) don't run node10 on our laptops. Github CI uses their own "flavour" of Ubuntu, with a newer nodejs version, so it's not picked up in the [eslint CI task](https://github.com/openstreetmap/openstreetmap-website/blob/87657108f6bd2a4afa41760dff1947a8349b28f8/.github/workflows/lint.yml#L38). If CI was running actual Ubuntu, with nodejs10, then it would have picked up this problem months ago and the eslint test would fail with the same error.

The preferred fix is the same as I wrote in that comment - we need to upgrade our Docker, Vagrant, CI and installation instructions all to Ubuntu 22.04.

If we wanted to prevent this from happening again, we need to rethink our CI system, so that it runs eslint (and rubocop, and other developer tools) on the actual version of Ubuntu that developers have installed, rather than the github-flavoured-ubuntu used in Github Actions. One way to do this would be to add eslint to the [docker CI](https://github.com/openstreetmap/openstreetmap-website/blob/master/.github/workflows/docker.yml), but I'd prefer to avoid making that even slower to run. I don't intend to work on this aspect though, since upgrading everything to 22.04 is needed anyway.

**Comment by gravitystorm** [comment]
> I never had eslint working as described in the docs here. I run this instead:

@AntonKhorev I'm happy to help debug why our instructions aren't working for you - if it's happening to you, it might be happening to other developers too and putting them off from contributing. So if you can provide more details (e.g. error messages from your attempts to run `bundle exec rails eslint` then that would be helpful and hopefully we can debug it together. If it's a different error message, it might be worth opening a fresh issue.

**Comment by gravitystorm** [comment]
> The preferred fix is the same as I wrote in that comment - we need to upgrade our Docker, Vagrant, CI and installation instructions all to Ubuntu 22.04.

This is now complete, as part of #4048 . So if you follow any of the supported installation approaches - either running vagrant, docker or direct installation onto Ubuntu 22.04, then `bundle exec eslint` will now work again.
