### ISSUE TITLE
NoMethodError: undefined method `exists?' for File:Class

### ISSUE THREAD

**Issue by ttimhzv** [openstreetmap/openstreetmap-website#4083]
### How to reproduce the issue?

Hi, im getting next error when executing `bundle exec rails db:create` command, i followed all steps in tutorial, i created new user and set it in database.yml, i tried setting password too. Any idea why am i getting next error.

```
rails aborted!
NoMethodError: undefined method 'exists?' for File:Class
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/oauth-0.4.7/lib/oauth/consumer.rb:13:in 'block in <class:Consumer>'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/oauth-0.4.7/lib/oauth/consumer.rb:12:in 'each'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/oauth-0.4.7/lib/oauth/consumer.rb:12:in '<class:Consumer>'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/oauth-0.4.7/lib/oauth/consumer.rb:9:in '<module:OAuth>'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/oauth-0.4.7/lib/oauth/consumer.rb:8:in '<main>'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in 'require'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in 'require'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/oauth-0.4.7/lib/oauth/client/helper.rb:2:in '<main>'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in 'require'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in 'require'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/oauth-0.4.7/lib/oauth.rb:10:in '<main>'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in 'require'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in 'require'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/oauth-plugin-0.5.1/lib/oauth-plugin.rb:1:in '<main>'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in 'require'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in 'require'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.26/lib/bundler/runtime.rb:60:in 'block (2 levels) in require'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.26/lib/bundler/runtime.rb:55:in 'each'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.26/lib/bundler/runtime.rb:55:in 'block in require'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.26/lib/bundler/runtime.rb:44:in 'each'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.26/lib/bundler/runtime.rb:44:in 'require'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.26/lib/bundler.rb:186:in 'require'
/root/openstreetmap-website/config/application.rb:7:in '<main>'
/root/openstreetmap-website/Rakefile:4:in 'require_relative'
/root/openstreetmap-website/Rakefile:4:in '<main>'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in 'load'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in 'load_rakefile'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:710:in 'raw_load_rakefile'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:104:in 'block in load_rakefile'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:186:in 'standard_exception_handling'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:103:in 'load_rakefile'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/commands/rake/rake_command.rb:20:in 'block in perform'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in 'with_application'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/commands/rake/rake_command.rb:18:in 'perform'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/command.rb:51:in 'invoke'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/commands.rb:18:in '<main>'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in 'require'
/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in 'require'
bin/rails:4:in '<main>'
```

**Comment by gravitystorm** [comment]
I haven't tested it thoroughly, but I suspect the answer is that you are using ruby 3.2 and that's exposing a problem with an old gem that we are using. 

Our CI uses 3.0 and 3.1, so my suggestion is to try one of those versions for now. It looks like you are using rbenv so that should be possible.

**Comment by tomhughes** [comment]
Yes it's an upstream issue that's outside our control. I'm using 3.2 but I've hacked my install of the gem. Unfortunately it's not really monkey patchable and the upstream gem is pretty much unmaintained so I may have to fork it at some point.

**Comment by tomhughes** [comment]
Well assuming we don't manage to drop OAuth 1 before then at least...

**Comment by tomhughes** [comment]
If anybody does want to hack their install you need to look at `consumer.rb` and at the top change this:

```ruby
    CA_FILES.each do |ca_file|
      if File.exists?(ca_file)
        CA_FILE = ca_file
        break
      end
    end
```

to this:

```ruby
    CA_FILES.each do |ca_file|
      if File.exist?(ca_file)
        CA_FILE = ca_file
        break
      end
    end
```

It's because it is class scope code that runs when the file is loaded that monkey patching is not really possible.

**Comment by ttimhzv** [comment]
Thanks for fast response, i downgraded ruby to 3.1.4 and its working now. Thanks again
