### ISSUE TITLE
Unable to start local server

### ISSUE THREAD

**Issue by watbywbarif** [openstreetmap/openstreetmap-website#4547]
### How to reproduce the issue?

I am following master/INSTALL.md to install the local server on Ubuntu 22.04

I am stuck at step: `sudo bundle exec rails test:all`

with error:
```
$ sudo bundle exec rails test:all
Coverage report generated for Minitest to /prep/map/osm/openstreetmap-website/coverage. 328 / 8738 LOC (3.75%) covered.
Lcov style coverage report generated for Minitest to coverage/lcov.info
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
/var/lib/gems/3.0.0/gems/selenium-webdriver-4.18.1/lib/selenium/webdriver/common/driver_finder.rb:30:in `rescue in path': Unable to obtain geckodriver using Selenium Manager; Unsuccessful command executed: ["/var/lib/gems/3.0.0/gems/selenium-webdriver-4.18.1/bin/linux/selenium-manager", "--browser", "firefox", "--language-binding", "ruby", "--output", "json"] (Selenium::WebDriver::Error::NoSuchDriverError)
/var/lib/gems/3.0.0/gems/selenium-webdriver-4.18.1/bin/linux/selenium-manager: 1: Syntax error: "(" unexpected
; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
        from /var/lib/gems/3.0.0/gems/selenium-webdriver-4.18.1/lib/selenium/webdriver/common/driver_finder.rb:27:in `path'
        from /var/lib/gems/3.0.0/gems/actionpack-7.1.3.2/lib/action_dispatch/system_testing/browser.rb:73:in `resolve_driver_path'
        from /var/lib/gems/3.0.0/gems/actionpack-7.1.3.2/lib/action_dispatch/system_testing/browser.rb:45:in `preload'
        from /var/lib/gems/3.0.0/gems/actionpack-7.1.3.2/lib/action_dispatch/system_testing/driver.rb:19:in `initialize'
        from /var/lib/gems/3.0.0/gems/actionpack-7.1.3.2/lib/action_dispatch/system_test_case.rb:159:in `new'
        from /var/lib/gems/3.0.0/gems/actionpack-7.1.3.2/lib/action_dispatch/system_test_case.rb:159:in `driven_by'
        from /prep/map/osm/openstreetmap-website/test/application_system_test_case.rb:10:in `<class:ApplicationSystemTestCase>'
        from /prep/map/osm/openstreetmap-website/test/application_system_test_case.rb:9:in `<top (required)>'
        from /var/lib/gems/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /var/lib/gems/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /var/lib/gems/3.0.0/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:34:in `require'
        from /prep/map/osm/openstreetmap-website/test/system/account_deletion_test.rb:1:in `<top (required)>'
        from /var/lib/gems/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /var/lib/gems/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /var/lib/gems/3.0.0/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:34:in `require'
        from /var/lib/gems/3.0.0/gems/railties-7.1.3.2/lib/rails/test_unit/runner.rb:51:in `block in load_tests'
        from /var/lib/gems/3.0.0/gems/railties-7.1.3.2/lib/rails/test_unit/runner.rb:51:in `each'
        from /var/lib/gems/3.0.0/gems/railties-7.1.3.2/lib/rails/test_unit/runner.rb:51:in `load_tests'
        from /var/lib/gems/3.0.0/gems/railties-7.1.3.2/lib/rails/test_unit/runner.rb:43:in `run'
        from /var/lib/gems/3.0.0/gems/railties-7.1.3.2/lib/rails/commands/test/test_command.rb:33:in `perform'
        from /var/lib/gems/3.0.0/gems/railties-7.1.3.2/lib/rails/commands/test/test_command.rb:46:in `all'
        from /var/lib/gems/3.0.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
        from /var/lib/gems/3.0.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /var/lib/gems/3.0.0/gems/railties-7.1.3.2/lib/rails/command/base.rb:178:in `invoke_command'
        from /var/lib/gems/3.0.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
        from /var/lib/gems/3.0.0/gems/railties-7.1.3.2/lib/rails/command/base.rb:73:in `perform'
        from /var/lib/gems/3.0.0/gems/railties-7.1.3.2/lib/rails/command.rb:71:in `block in invoke'
        from /var/lib/gems/3.0.0/gems/railties-7.1.3.2/lib/rails/command.rb:149:in `with_argv'
        from /var/lib/gems/3.0.0/gems/railties-7.1.3.2/lib/rails/command.rb:69:in `invoke'
        from /var/lib/gems/3.0.0/gems/railties-7.1.3.2/lib/rails/commands.rb:18:in `<main>'
        from /var/lib/gems/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /var/lib/gems/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from bin/rails:4:in `<main>'
/var/lib/gems/3.0.0/gems/selenium-webdriver-4.18.1/lib/selenium/webdriver/common/selenium_manager.rb:136:in `run': Unsuccessful command executed: ["/var/lib/gems/3.0.0/gems/selenium-webdriver-4.18.1/bin/linux/selenium-manager", "--browser", "firefox", "--language-binding", "ruby", "--output", "json"] (Selenium::WebDriver::Error::WebDriverError)
/var/lib/gems/3.0.0/gems/selenium-webdriver-4.18.1/bin/linux/selenium-manager: 1: Syntax error: "(" unexpected
        from /var/lib/gems/3.0.0/gems/selenium-webdriver-4.18.1/lib/selenium/webdriver/common/selenium_manager.rb:42:in `driver_path'
        from /var/lib/gems/3.0.0/gems/selenium-webdriver-4.18.1/lib/selenium/webdriver/common/driver_finder.rb:28:in `path'
        from /var/lib/gems/3.0.0/gems/actionpack-7.1.3.2/lib/action_dispatch/system_testing/browser.rb:73:in `resolve_driver_path'
        from /var/lib/gems/3.0.0/gems/actionpack-7.1.3.2/lib/action_dispatch/system_testing/browser.rb:45:in `preload'
        from /var/lib/gems/3.0.0/gems/actionpack-7.1.3.2/lib/action_dispatch/system_testing/driver.rb:19:in `initialize'
        from /var/lib/gems/3.0.0/gems/actionpack-7.1.3.2/lib/action_dispatch/system_test_case.rb:159:in `new'
        from /var/lib/gems/3.0.0/gems/actionpack-7.1.3.2/lib/action_dispatch/system_test_case.rb:159:in `driven_by'
        from /prep/map/osm/openstreetmap-website/test/application_system_test_case.rb:10:in `<class:ApplicationSystemTestCase>'
        from /prep/map/osm/openstreetmap-website/test/application_system_test_case.rb:9:in `<top (required)>'
        from /var/lib/gems/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /var/lib/gems/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /var/lib/gems/3.0.0/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:34:in `require'
        from /prep/map/osm/openstreetmap-website/test/system/account_deletion_test.rb:1:in `<top (required)>'
        from /var/lib/gems/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /var/lib/gems/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /var/lib/gems/3.0.0/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:34:in `require'
        from /var/lib/gems/3.0.0/gems/railties-7.1.3.2/lib/rails/test_unit/runner.rb:51:in `block in load_tests'
        from /var/lib/gems/3.0.0/gems/railties-7.1.3.2/lib/rails/test_unit/runner.rb:51:in `each'
        from /var/lib/gems/3.0.0/gems/railties-7.1.3.2/lib/rails/test_unit/runner.rb:51:in `load_tests'
        from /var/lib/gems/3.0.0/gems/railties-7.1.3.2/lib/rails/test_unit/runner.rb:43:in `run'
        from /var/lib/gems/3.0.0/gems/railties-7.1.3.2/lib/rails/commands/test/test_command.rb:33:in `perform'
        from /var/lib/gems/3.0.0/gems/railties-7.1.3.2/lib/rails/commands/test/test_command.rb:46:in `all'
        from /var/lib/gems/3.0.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
        from /var/lib/gems/3.0.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /var/lib/gems/3.0.0/gems/railties-7.1.3.2/lib/rails/command/base.rb:178:in `invoke_command'
        from /var/lib/gems/3.0.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
        from /var/lib/gems/3.0.0/gems/railties-7.1.3.2/lib/rails/command/base.rb:73:in `perform'
        from /var/lib/gems/3.0.0/gems/railties-7.1.3.2/lib/rails/command.rb:71:in `block in invoke'
        from /var/lib/gems/3.0.0/gems/railties-7.1.3.2/lib/rails/command.rb:149:in `with_argv'
        from /var/lib/gems/3.0.0/gems/railties-7.1.3.2/lib/rails/command.rb:69:in `invoke'
        from /var/lib/gems/3.0.0/gems/railties-7.1.3.2/lib/rails/commands.rb:18:in `<main>'
        from /var/lib/gems/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /var/lib/gems/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by tomhughes** [comment]
You need to install geckodriver.
