### ISSUE TITLE
HTTP 500 when trying to open a diary entry via a link

### ISSUE THREAD

**Issue by deevroman** [openstreetmap/openstreetmap-website#4890]
### URL

https://www.openstreetmap.org/user/SomeoneElse/diary/404191

### How to reproduce the issue?

1. Open link

### Screenshot(s) or anything else?

<img width="1295" alt="Снимок экрана 2024-06-10 в 16 16 17" src="https://github.com/openstreetmap/openstreetmap-website/assets/25708359/ab226ef6-3b91-4e93-9376-3c3908888d7e">

p.s. the entry is visible in the list of user entries https://www.openstreetmap.org/user/SomeoneElse/diary

**Comment by SomeoneElseOSM** [comment]
If it would help, I can edit it to see if that "fixes" anything - I'll not do that yet though.

**Comment by tomhughes** [comment]
Log from production:

```
[ZmcC5886Iahkww7zrNg8dgAAJy0] Started GET "/user/SomeoneElse/diary/404191" for xxx at 2024-06-10 13:43:03 +0000
[ZmcC5886Iahkww7zrNg8dgAAJy0] Processing by DiaryEntriesController#show as HTML
[ZmcC5886Iahkww7zrNg8dgAAJy0]   Parameters: {"display_name"=>"SomeoneElse", "id"=>"404191"}
[ZmcC5886Iahkww7zrNg8dgAAJy0]   Rendered layout layouts/site.html.erb (Duration: 89.8ms | Allocations: 23500)
[ZmcC5886Iahkww7zrNg8dgAAJy0] Completed 500 Internal Server Error in 129ms (Allocations: 32521)
[ZmcC5886Iahkww7zrNg8dgAAJy0]   
[ZmcC5886Iahkww7zrNg8dgAAJy0] ActionView::Template::Error (bad URI(is not URI?): "https://map.atownsend.org.uk/tmp/Screenshot 2024-05-29 224839.png"):
[ZmcC5886Iahkww7zrNg8dgAAJy0]     21: <% end -%>
[ZmcC5886Iahkww7zrNg8dgAAJy0]     22: <%= tag.link :rel => "search", :type => "application/opensearchdescription+xml", :title => "OpenStreetMap Search", :href => asset_path("osm.xml") %>
[ZmcC5886Iahkww7zrNg8dgAAJy0]     23: <%= tag.meta :name => "description", :content => "OpenStreetMap is the free wiki world map." %>
[ZmcC5886Iahkww7zrNg8dgAAJy0]     24: <%= opengraph_tags(@title, @og_image) %>
[ZmcC5886Iahkww7zrNg8dgAAJy0]     25: <% if flash[:matomo_goal] -%>
[ZmcC5886Iahkww7zrNg8dgAAJy0]     26: <%= tag.meta :name => "matomo-goal", :content => flash[:matomo_goal] %>
[ZmcC5886Iahkww7zrNg8dgAAJy0]     27: <% end -%>
[ZmcC5886Iahkww7zrNg8dgAAJy0]   
[ZmcC5886Iahkww7zrNg8dgAAJy0] app/helpers/open_graph_helper.rb:7:in `opengraph_tags'
[ZmcC5886Iahkww7zrNg8dgAAJy0] app/views/layouts/_meta.html.erb:24
[ZmcC5886Iahkww7zrNg8dgAAJy0] app/views/layouts/_head.html.erb:11
[ZmcC5886Iahkww7zrNg8dgAAJy0] app/views/layouts/_head.html.erb:1
[ZmcC5886Iahkww7zrNg8dgAAJy0] app/views/layouts/site.html.erb:3
[ZmcC5886Iahkww7zrNg8dgAAJy0] config/initializers/compressed_requests.rb:27:in `call'
[ZmcC5886Iahkww7zrNg8dgAAJy0] config/initializers/cors.rb:9:in `call'
[ZmcC5886Iahkww7zrNg8dgAAJy0] Processing by ErrorsController#internal_server_error as HTML
[ZmcC5886Iahkww7zrNg8dgAAJy0]   Parameters: {"display_name"=>"SomeoneElse", "id"=>"404191"}
[ZmcC5886Iahkww7zrNg8dgAAJy0]   Rendered layout layouts/error.html.erb (Duration: 4.5ms | Allocations: 1996)
[ZmcC5886Iahkww7zrNg8dgAAJy0] Completed 500 Internal Server Error in 8ms (Views: 5.7ms | ActiveRecord: 0.0ms | Allocations: 2761)
```

**Comment by AntonKhorev** [comment]
Caused by spaces in image url. Kramdown doesn't urlencode them in its document tree.

**Comment by nenad-vujicic** [comment]
Dear @deevroman ,

Perhaps you could try to edit it and replace ' ' (space characters) with %20 (in above case URL should be https://map.atownsend.org.uk/tmp/Screenshot%202024-05-29%20224839.png) as a temporary workaround?

Thanks,
Nenad.

**Comment by SomeoneElseOSM** [comment]
I''v taken the spaces out.
