### ISSUE TITLE
We need to move away from dartsass-ruby

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/openstreetmap-website#5313]
We are currently using `dartsass-ruby` as a dependency of `dartsass-sprockets` but v1.x of the `uri` gem has an ABI change which breaks it:

```
bin/rails aborted!
ArgumentError: wrong number of arguments (given 1, expected 0) (ArgumentError)
/home/tom/.bundle/ruby/3.3.0/gems/uri-1.0.1/lib/uri/rfc3986_parser.rb:73:in `initialize'
/home/tom/.bundle/ruby/3.3.0/gems/dartsass-ruby-3.0.2/lib/sassc/url.rb:5:in `new'
/home/tom/.bundle/ruby/3.3.0/gems/dartsass-ruby-3.0.2/lib/sassc/url.rb:5:in `<module:URL>'
/home/tom/.bundle/ruby/3.3.0/gems/dartsass-ruby-3.0.2/lib/sassc/url.rb:4:in `<module:SassC>'
/home/tom/.bundle/ruby/3.3.0/gems/dartsass-ruby-3.0.2/lib/sassc/url.rb:3:in `<main>'
/home/tom/.bundle/ruby/3.3.0/gems/dartsass-ruby-3.0.2/lib/sassc.rb:54:in `require_relative'
/home/tom/.bundle/ruby/3.3.0/gems/dartsass-ruby-3.0.2/lib/sassc.rb:54:in `<main>'
```

As `dartsass-ruby` has been abandoned it seems either `dartsass-sprockets` will need updating or we will need to replace it.

**Comment by tomhughes** [comment]
Ah it has already been changed in `dartsass-sprockets` but we have a version lock on `sass-embedded` which is stopping it from updating.

**Comment by tomhughes** [comment]
The version lock is from 41f13ac73a740b16bce708b23db8b2cdb6d24d1f and it seems our bootstrap is still too old to avoid the warnings.
