### ISSUE TITLE
Search: should silently hide failed lookups (Error contacting nominatim.openstreetmap.org: #<REXML::ParseException)

### ISSUE THREAD

**Issue by sladen** [openstreetmap/openstreetmap-website#969]
During the course of this morning, Nomination lookups appear to have been intermittently returning HTML-encapsulated error messages instead of result snippets.  In this case the Search handler shows the error verbatim flooding the search result area.  Ideally if a search provider fails it should show as though there were no valid results from that provider.

To reproduce:

  1. Enter 'x' in the Search box and Click 'Go'

What happens:

  2. Observe that the search results show an error 

What should happen:

  2. The search results from Nomination should be empty or show "No results found"/"No results returned"; allowing the Geonames results to be visible above the fold.

The error message (shown in red) is being generated in `app/controllers/geocoder_controller.rb#L189`  and is:

```
Error contacting nominatim.openstreetmap.org: #<REXML::ParseException: Missing end tag for 'p' (got "body") Line: 14 Position: 513 Last 80 unconsumed characters: > /usr/lib/ruby/1.9.1/rexml/parsers/baseparser.rb:335:in `pull_event' /usr/lib/ruby/1.9.1/rexml/parsers/baseparser.rb:183:in `pull' /usr/lib/ruby/1.9.1/rexml/parsers/treeparser.rb:22:in `parse' /usr/lib/ruby/1.9.1/rexml/document.rb:249:in `build' /usr/lib/ruby/1.9.1/rexml/document.rb:43:in `initialize' /srv/www.openstreetmap.org/rails/app/controllers/geocoder_controller.rb:293:in `new' /srv/www.openstreetmap.org/rails/app/controllers/geocoder_controller.rb:293:in `fetch_xml' /srv/www.openstreetmap.org/rails/app/controllers/geocoder_controller.rb:145:in `search_osm_nominatim' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:198:in `process_action' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_controller/metal/rendering.rb:10:in `process_action' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action' /var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call' /var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call' /var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile' /var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call' /var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call' /var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks' /var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks' /var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:19:in `process_action' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_controller/metal/rescue.rb:29:in `process_action' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action' /var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument' /var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument' /var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action' /var/lib/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:137:in `process' /var/lib/gems/1.9.1/gems/actionview-4.2.1/lib/action_view/rendering.rb:30:in `process' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_controller/metal.rb:196:in `dispatch' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_controller/metal.rb:237:in `block in action' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:74:in `call' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:43:in `serve' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:43:in `block in serve' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `each' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `serve' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:819:in `call' /var/lib/gems/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!' /var/lib/gems/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call' /var/lib/gems/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!' /var/lib/gems/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call' /var/lib/gems/1.9.1/gems/omniauth-1.2.2/lib/omniauth/builder.rb:59:in `call' /var/lib/gems/1.9.1/gems/oauth-plugin-0.5.1/lib/oauth/rack/oauth_filter.rb:75:in `call' /var/lib/gems/1.9.1/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call' /srv/www.openstreetmap.org/rails/config/initializers/cors.rb:9:in `call' /var/lib/gems/1.9.1/gems/http_accept_language-2.0.5/lib/http_accept_language/middleware.rb:14:in `call' /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/etag.rb:24:in `call' /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/conditionalget.rb:25:in `call' /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/head.rb:13:in `call' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/middleware/flash.rb:260:in `call' /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:225:in `context' /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:220:in `call' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/middleware/cookies.rb:560:in `call' /var/lib/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call' /var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `call' /var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `_run_callbacks' /var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_call_callbacks' /var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call' /var/lib/gems/1.9.1/gems/railties-4.2.1/lib/rails/rack/logger.rb:38:in `call_app' /var/lib/gems/1.9.1/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `block in call' /var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `block in tagged' /var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:26:in `tagged' /var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `tagged' /var/lib/gems/1.9.1/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `call' /var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/middleware/request_id.rb:21:in `call' /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call' /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/runtime.rb:18:in `call' /var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call' /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/sendfile.rb:113:in `call' /var/lib/gems/1.9.1/gems/railties-4.2.1/lib/rails/engine.rb:518:in `call' /var/lib/gems/1.9.1/gems/railties-4.2.1/lib/rails/application.rb:164:in `call' /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:89:in `process_request' /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request' /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop' /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:414:in `block (3 levels) in start_threads' /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception' ... Missing end tag for 'p' (got "body") Line: 14 Position: 513 Last 80 unconsumed characters: Line: 14 Position: 513 Last 80 unconsumed characters: 
```
Actual request grabbed with Firebug:
```GET /geocoder/search_osm_nominatim?query=northon+bridge&xhr=1&zoom=11&minlon=-2.3785400390625&minlat=52.985857111006744&maxlon=-1.7255401611328125&maxlat=53.23974251959408 HTTP/1.1```
![osm-nomination-broken](https://cloud.githubusercontent.com/assets/27120/7626390/6f8b1050-fa00-11e4-8bb8-ac182952bb30.png)
Actual response:
```200 OK```
and
```html
<p class="search_results_error">Error contacting nominatim.openstreetmap.org: #&lt;REXML::ParseException 
: Missing end tag for &#39;p&#39; (got &quot;body&quot;)
Line: 14
Position: 513
Last 80 unconsumed characters:
&gt;
/usr/lib/ruby/1.9.1/rexml/parsers/baseparser.rb:335:in `pull_event&#39;
/usr/lib/ruby/1.9.1/rexml/parsers/baseparser.rb:183:in `pull&#39;
/usr/lib/ruby/1.9.1/rexml/parsers/treeparser.rb:22:in `parse&#39;
/usr/lib/ruby/1.9.1/rexml/document.rb:249:in `build&#39;
/usr/lib/ruby/1.9.1/rexml/document.rb:43:in `initialize&#39;
/srv/www.openstreetmap.org/rails/app/controllers/geocoder_controller.rb:293:in `new&#39;
/srv/www.openstreetmap.org/rails/app/controllers/geocoder_controller.rb:293:in `fetch_xml&#39;
/srv/www.openstreetmap.org/rails/app/controllers/geocoder_controller.rb:145:in `search_osm_nominatim
&#39;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action
&#39;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:198:in `process_action&#39
;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_controller/metal/rendering.rb:10:in `process_action
&#39;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action
&#39;
/var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call&#39;
/var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call&#39;
/var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:555:in `block (2 levels
) in compile&#39;
/var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call&#39;
/var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call&#39;
/var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks&#39
;
/var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks
&#39;
/var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks&#39
;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:19:in `process_action
&#39;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_controller/metal/rescue.rb:29:in `process_action
&#39;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:32:in `block
 in process_action&#39;
/var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument
&#39;
/var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in 
`instrument&#39;
/var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument&
#39;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action
&#39;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action
&#39;
/var/lib/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action
&#39;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:137:in `process&#39;
/var/lib/gems/1.9.1/gems/actionview-4.2.1/lib/action_view/rendering.rb:30:in `process&#39;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_controller/metal.rb:196:in `dispatch&#39;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch
&#39;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_controller/metal.rb:237:in `block in action&#39
;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:74:in `call&#39;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch&#39
;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:43:in `serve&#39;

/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:43:in `block in serve
&#39;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `each&#39;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `serve&#39;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:819:in `call&#39;

/var/lib/gems/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!&#39;
/var/lib/gems/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call&#39;
/var/lib/gems/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!&#39;
/var/lib/gems/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call&#39;
/var/lib/gems/1.9.1/gems/omniauth-1.2.2/lib/omniauth/builder.rb:59:in `call&#39;
/var/lib/gems/1.9.1/gems/oauth-plugin-0.5.1/lib/oauth/rack/oauth_filter.rb:75:in `call&#39;
/var/lib/gems/1.9.1/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call&#39;
/srv/www.openstreetmap.org/rails/config/initializers/cors.rb:9:in `call&#39;
/var/lib/gems/1.9.1/gems/http_accept_language-2.0.5/lib/http_accept_language/middleware.rb:14:in `call
&#39;
/var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/etag.rb:24:in `call&#39;
/var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/conditionalget.rb:25:in `call&#39;
/var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/head.rb:13:in `call&#39;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/middleware/flash.rb:260:in `call&#39;
/var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:225:in `context&#39;
/var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:220:in `call&#39;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/middleware/cookies.rb:560:in `call&#39
;
/var/lib/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool
.rb:649:in `call&#39;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in
 call&#39;
/var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `call&#39;
/var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `_run_callbacks&#39
;
/var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_call_callbacks
&#39;
/var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks&#39
;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call&#39
;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call&#39
;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call
&#39;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call
&#39;
/var/lib/gems/1.9.1/gems/railties-4.2.1/lib/rails/rack/logger.rb:38:in `call_app&#39;
/var/lib/gems/1.9.1/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `block in call&#39;
/var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `block in tagged
&#39;
/var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:26:in `tagged&#39;

/var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `tagged&#39;

/var/lib/gems/1.9.1/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `call&#39;
/var/lib/gems/1.9.1/gems/actionpack-4.2.1/lib/action_dispatch/middleware/request_id.rb:21:in `call&#39
;
/var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call&#39;
/var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/runtime.rb:18:in `call&#39;
/var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/cache/strategy/local_cache_middleware
.rb:28:in `call&#39;
/var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/sendfile.rb:113:in `call&#39;
/var/lib/gems/1.9.1/gems/railties-4.2.1/lib/rails/engine.rb:518:in `call&#39;
/var/lib/gems/1.9.1/gems/railties-4.2.1/lib/rails/application.rb:164:in `call&#39;
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:89:in `process_request&
#39;
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request
&#39;
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop&#39;

/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:414:in `block (3 levels) in start_threads
&#39;
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception
&#39;
...
Missing end tag for &#39;p&#39; (got &quot;body&quot;)
Line: 14
Position: 513
Last 80 unconsumed characters:

Line: 14
Position: 513
Last 80 unconsumed characters:
</p>```

**Comment by tomhughes** [comment]
Just a snippet would have done you know...

We don't want to "hide" the failures though, we just want to report them better.
